In [ ]:
'''
ACD - best for relation detection
'''

In [2]:
import numpy as np

In [31]:
# wrong order + right relation = 0.606
s1 = np.array([
    [[20, 10, 0], [50, 30, 100]], 
    [[50, 30, 100], [180, 20, 20]], 
    [[180, 20, 20], [30, 15, 0]]
], dtype=np.double)

s2 = np.array([
    [[180, 20, 20], [20, 10, 5]], 
    [[20, 10, 5], [30, 16, 1]], 
    [[30, 16, 1], [50, 29, 120]]
], dtype=np.double)

In [28]:
# right order + right relation = 0.307
s1 = np.array([
    [[20, 10, 0], [50, 30, 100]], 
    [[50, 30, 100], [180, 20, 20]], 
    [[180, 20, 20], [30, 15, 0]]
], dtype=np.double)

s2 = np.array([
    [[18, 12, 5], [47, 35, 110]], 
    [[47, 35, 110], [200, 18, 40]], 
    [[200, 18, 40], [30, 9, 4]]
], dtype=np.double)

In [3]:
# right order + wrong relation = 2.135
s1 = np.array([
    [[20, 10, 0], [50, 30, 100]], 
    [[50, 30, 100], [180, 20, 20]], 
    [[180, 20, 20], [30, 15, 0]]
], dtype=np.double)

s2 = np.array([
    [[20, 10, 20], [180, 20, 100]], 
    [[180, 20, 100], [50, 35, 40]], 
    [[50, 35, 40], [30, 15, 30]]
], dtype=np.double)

In [33]:
# calculate matrix
def autocorrelation_matrix(data):
    data_flat = data.reshape(-1, 3)  # 展平数据为 (N, 3) 形状
    return np.corrcoef(data_flat, rowvar=False)

autocorr_s1 = autocorrelation_matrix(s1)
autocorr_s2 = autocorrelation_matrix(s2)
print(autocorr_s1)
print(autocorr_s2)

[[ 1.          0.07540693 -0.18151373]
 [ 0.07540693  1.          0.94956293]
 [-0.18151373  0.94956293  1.        ]]
[[1.         0.38655248 0.10280828]
 [0.38655248 1.         0.87141575]
 [0.10280828 0.87141575 1.        ]]


In [34]:
#  l2 to calculate ACD
acd = np.sqrt(np.sum((autocorr_s1 - autocorr_s2) ** 2))
print("自相关差异 (ACD):", acd)

自相关差异 (ACD): 0.6062302177125646


In [26]:
#  Frobenius to calculate ACD
acd = np.linalg.norm(autocorr_s1 - autocorr_s2, ord='fro')

print("自相关差异 (ACD):", acd)

自相关差异 (ACD): 0.6062302177125646
